# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7980500c9c6fa10a176de6a88517aa3f878732950e78e011f97c2d31298795afd204aa041a12901d446fec559283bd680a36f80c1b56facd9baa3f7f2a2409b1

test:
  secret_key_base: 86503fee3ff0f4c5a34c5009d70d3c38afa6656da853884d278e83e17e74cf4cfb6c7b6c08a6885c279685fccb7f42fade747e531f73e01f4c25207769547d4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
